version: '3.8'

services:
  db:
    restart: always
    image: postgres:8
    environment:
      - POSTGRES_DATABASE=atom_bella
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2405
      - POSTGRES_ROOT_PASSWORD=2405
    volumes:
      - db-data:/var/lib/postgres
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      backend:

  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    networks:
      backend:
    depends_on:
      - db
    environment:
    - DEBUG=True
    - DB_NAME=atom_bella
    - DB_USERNAME=postgres
    - DB_PASSWORD=2405
    - DB_HOST=db
    - DB_PORT=5432
    volumes:
      - web-media:/code/web-application/media


volumes:
  db-data:
  web-media:

networks:
  backend: